language: java
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
  - $HOME/.m2/
before_script:
  - mvn -v
script:  mvn package
jdk: openjdk10
env: TERM=dumb
